baseURL = "https://medexe077.github.io/blog/"
languageCode = "en-us"
title = "fr0st Blog"
theme = "LoveIt"

[params]
  version = "0.2.X"
  description = "My CTF writeups & security research"
  defaultTheme = "dark"

  [params.author]
    name = "fr0st"
    email = "mohamed_kheddari@etu.univ-blida.dz"
    link = "https://github.com/medexe077"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = ""
      title = "fr0st"
      subtitle = "CTF writeups & security research"
      typeit = false
      social = true
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "medexe077"
    Linkedin = "Mohamed KHEDDARI"
    Email = "mohamed_kheddari@etu.univ-blida.dz"

  [params.page]
    enable = true
    [params.page.toc]
      enable = true
    [params.page.code]
      copy = true
    [params.page.share]
      enable = false

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
