baseURL = "https://medexe077.github.io/blog/"
languageCode = "en-us"
title = "fr0st Blog"
theme = "LoveIt"

[params]
  version = "0.2.X"
  description = "CTF writeups & security research"
  defaultTheme = "dark"

  [params.author]
    name = "fr0st"
    email = ""
    link = "https://github.com/medexe077"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = ""
      title = "fr0st"
      subtitle = "CTF writeups & security research"
      typeit = false
      social = true

  [params.social]
    GitHub = "medexe077"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
